### PR TITLE
Specify a travel/landing target for Mission NPCs

### PR DESCRIPTION
**Pull request by tehhowch**
NPCs can be given a travel plan and will follow it.

 - In the mission NPC description, at the same level as its origin system, or the ship / fleet designator, provide the token `waypoint` or the token-value pair of `waypoint someplace`, where `someplace` is an evaluated system name. 
If only `waypoint` is given, the mission's destination system is used.
 - In the mission NPC description, at the same level as its origin system, or the ship / fleet designator, provide the token `land`, or the token-value pair `land someplace` where `someplace` is an evaluated landable planet. You can provide more than one `someplace`.
If only `land` is given, the mission destination planet is used. 
These planets should be accessible to the NPC. These planets does not have to be in the mission destination system.

Bonus features:
 - If instead of `waypoint`, the word `patrol` is encountered, and multiple systems are given, the NPC will travel between the listed systems, in the order given. When reaching the final system, a course for the first specified system is set, e.g. `A->B->C->D->A` and not `A->B->C->D->C->B->A`. This repeats until the mission is failed/completed/NPC killed.
 - If instead of `land`, the word `visit` is encountered, the NPC will temporarily land on the listed planet(s). 
If paired with `patrol`, the planet will invoke the visiting behavior once per patrol cycle.The behavior is otherwise identical to `land`: they will not invoke an automatic TRAVEL_TO.

As of 703dbe1:
Invoking TRAVEL_TO with `waypoint` will make the NPC ignore the player's actions. It will stop for combat. This can be combined with `staying` to make the NPC stay in the system described by `waypoint`. If `personality staying` is not used, the NPC will travel to the system and then return to the player, wherever the player is located.
Invoking LAND_ON with `land` will make the NPC ignore the player's actions once arriving in the system containing the specified planet. It will **not** make the NPC travel towards that system automatically. LAND_ON without TRAVEL_TO can be used to set a trap for an NPC in an otherwise friendly system.

These parameters should allow content creators significant flexibility, especially with defining adversarial targets or targets that should not originate or appear to coordinate with the player. Note that if the NPC will follow normal engagement rules - that is, combat is the number one priority. If you wish the NPC to flee when the player attacks it, it should have the `fleeing`, or `pacifist` personality, or even both. Unlike regular `fleeing` NPCs, specifying a travel directive with waypoint/patrol/land/visit will not allow the fleeing NPC to be deleted, unless it has completed all travel specified for it.

Implementation checklist
- [x] TRAVEL_TO allows NPCs to move to systems that are not the player's system
- [x] Missions can declare an explicit TRAVEL_TO destination system, or inherit the mission's destination system as the target. Thus, NPCs can be spawned in any system (as already possible) and sent to any arbitrary system (this bit's new).
- [x] Track down the issue(s) that prevent NPC.Save() from saving the NPC's travel plan.
- [x] Allow `land` to default to the mission destination planet
- [x] Deactivate TRAVEL_TO upon arrival in the destination system
- [x] Issue LAND_ON order when the target planet is in the NPC's system. This is related to deactivating TRAVEL_TO.
- [x] Prioritize TRAVEL_TO even when the player is present in the NPC's system (e.g. no waiting around)
- [x] Handle possible issues associated with deleting the NPC ship after completion of LAND_ON
- [x] Test religiously:
    - Does the NPC follow its travel plan instead of the player's, if the player jumps when in the NPC's system?
    - Does the NPC move to its destination even if given `personality staying`?
    - Does the NPC engage hostiles it encounters (this requires it to be in the player's system) or simply jump out of the system to continue its travel plan?
    - What does the NPC do after reaching its destination? If `staying`, it should remain there. If not, it should attempt to rendezvous with the player.
    - Do the `destination` and `land` keywords get written to the mission file, for use on reload?
    - Do the NPCs utilize non-restricted wormholes as needed?
    - Do the NPCs refuel on non-restricted planets as needed?

### CODE REVIEW

**Comment by tehhowch** [comment]
Todo
[ ] Deactivate TRAVEL_TO upon arrival in the destination system
[ ] Issue LAND_ON order when the target planet is in the NPC's system
[ ] Handle issues associated with deleting the NPC ship after completion of LAND_ON
[x] Track down the issue(s) that prevent NPC.Save() from saving the NPC's travel plan.
[ ] Prioritize TRAVEL_TO even when the player is present in the NPC's system.
[ ] Test religiously.

**Comment by tehhowch** [comment]
as of afc929a, `land` will inherit the target of the mission destination planet. But, `destination <system>` does not have to point to the same system as the mission's destination, and thus 
```
destination <planet>
npc
    destination <systemN>
    land
```
is not quite intuitive, as it will instantiate to `land <planet>`, and \<systemN\> may not contain <planet>
I'm not sure how best to resolve this ambiguity, or if it should be, as I don't think we want to iterate stellarobjects to choose a random planet in \<systemN\>.
Thoughts welcomed.

**Comment by Elyssaen** [comment]
Isn't an npc `destination` and an npc `land` mutually exclusive anyway? I've been assuming that:

```
npc
    land Earth
```

should first make them travel to the Sol system, in which case having both `destination` _and_ `land` is a mistake on the side of the content creator. If a content creator writes `destination Sirius` and `land Earth`, as long as it does something consistent and it's clear in documentation that what they've done makes no sense, I think it's okay.

**Comment by tehhowch** [comment]
Right now they are not mutually exclusive. You can direct an NPC to travel System A, and (currently), if it is told to land on B, it would land on B if B's system is one of those chosen for its travel path to A.

**Comment by Elyssaen** [comment]
Ah. I think the data file entries are mutually exclusive: simultaneously go to system A and planet B. I think, like `personality timid heroic` or `personality staying fleeing`, it's just not a logical way to set up an NPC.

As for what should happen, it should probably take one set of orders only.

**Comment by tehhowch** [comment]
Right now, `land` is a subservient directive - it doesn't trigger any orders to be issued until the escort arrives in that system. This means it can serve as a silent mission twist. Consider a mission that asks you to escort a freighter of illegal cargo from one nullsec system to a 2nd nullsec system that is joined by two paths: 1 is long, composed solely of nullsec systems with high pirate activity, and the other is very short, but passes through a tightly regulated system. If the player approaches this like a standard "Escort to ..." job, they will leave the escort in the dust and jump through high-security straight to the destination, expecting the freighter to follow and nothing "bad" to happen. But, they will find out that the freighter gets "caught" in the high-sec system, and deletes itself instead. To complete the mission, they will have to lead the freighter around the loop, taking care not to get too far ahead that the freighter jumps into the high-sec system.


Remaining work:
 - wormhole routing
 - staying + land-to-refuel
 - test ShipEvents for NPCs with `land`
 - decision regarding `land` & `destination`
 - test meticulously
 - PR to upstream :eagle:

**Comment by Elyssaen** [comment]
You coding after all? And not on Discord?

**Comment by Elyssaen** [comment]
Update that I was writing earlier... (you know most of this now.)

#### `land` directive being subservient
Agreed. I think _all_ existing escort jobs would benefit from being given `land` (at destination). It'd be a nice immersion boost to see them actually go to land at their destination, and would allow you to cover them vs. any pirates.

I've added ShipEvent::LAND, so with this it's not even necessary to use `save` or `accompany`, or to have to 'hand in' your escort job at the same place you escorted them to.

#### Random walk
I noticed that if an NPC has `land` and `staying`, but no `destination`, it will engage in random travel. This combination makes no sense, but a mission NPC reverting to random travel isn't intuitive. I've done a commit to make staying take over in this case.

#### Enhancements
I asked about on Discord and we ended up thinking about significant enhancements, so my own task list right now is looking like:

- [x] Set up a new ShipEvent for landing.
- [x] Set up a new NPC success condition for landing.
- [x] Create a vector of destinations so you can enter _multiple_ successive destinations, e.g., `destination Sol Alnitak  Wezen`.
- [x] Create a new `patrol` directive, identical to `destination` except 1) it must have `child.Size >= 3` and 2) once the last system is reached, it routes back to the first.
- [x] Look into a `visit` directive, which is like `land` but takes back off again. My main concern is that done naïvely it will make a ship constantly land and take off. If it only runs once, it isn't compatible with `patrol` (no A <-> B route landing on either side). Seems like it'd need to trigger only when entering the system from another system.
- [ ] Bug fixes: will post possible issues in a moment.

**Comment by Elyssaen** [comment]
- [x] If they end up in a system in which they can't refuel, they get 'stuck' even if they have a ramscoop (and they don't plan for this contingency). Need to confirm.
- [x] They don't respect waiting anymore. waiting/land should work.
- [ ] If I attack the target in-system, a) they get completely distracted fighting me instead of trying to land (does timid/heroic affect this?), and b) if I cloak, they try to land but can't seem to manage it. In fact, they seem to in some cases end up /following/ my cloaked ship.
- [x] Not sure they're landing to refuel anymore, since adding my multi-destination.

**Comment by tehhowch** [comment]
Re: waiting: according to the wiki `waiting` means that the ship doesn't launch from the planet you were on, it was `waiting` in space. Aside from that, the bit about "follows you" is just normal "I'm an escort" behavior. (grepping the source files confirms - the only mentions of `waiting` are in Engine::Place). 
If we resort to wiki behavior description, giving the `land` or 'destination` directives to a `waiting` NPC would be an error by the mission creator.
In my mind, the reason one might specify `waiting` is not because they want normal escort behavior, but because they do not want the NPC to take off from the planet with you. If this is how we treat `waiting`, then there is nothing additional we need to do, as `waiting` can be combined with travel directives.

For missions in which you are to attack the NPC and they are supposed to try to deliver something somewhere else and not fight you, I think these NPCs also need `fleeing` or `coward`. Omitting them could be a mission creator error. I do not believe we have a chance to merge if we refactor all the AI::MoveX to prioritize following travel orders vs defending ones ship vs an aggressor (or otherwise engaging hostiles). IMO, the fleeing & coward personalities were created to fill this niche behavior. `Coward` might need a touch-up, as a quick check shows that it just forces no parent, not no target. `Fleeing` does enforce 'no target', which means only refuel, assist disabled, or jump actions will get done.

**Comment by Elyssaen** [comment]
Ah, I think I've misunderstood `waiting`. I read it as them not going anywhere until you enter the system they're in, and only then following you. Scratch that then (though that would be a useful trait, and _would_be compatible with `land` directives, just not `destination`).

I've never quite been straight about the behaviour of `coward`, `timid`, `fleeing`, etc., as I haven't used them, but from the sound of it the problem is solvable with them (or very nearly), so that's great.

Pushed a commit that makes `patrol` work onto my copy branch.

The idea of a `visit` directive is from Amazinite, and I think it's generally a good one, but I'm not looking forward to working out how to code it. The idea is that it's a non-permanent `land`, and might be used with `patrol A B` as `visit a b`, having them land on either side. But some thought is needed for how best to get it to not do an infinite loop of visit-landings, and also not do it just once and give up.

Some sort of "is it a different day" or "have we changed systems since" measure could work, but maybe it can be done with `destinationQueue` instead (that's the position we're through the list of destinations). Perhaps we could delete `visit` locations as we go, but when we reset `destinationQueue` at the end of a patrol, we reload the `visit` locations.

It'd mean, though, that with `patrol A B C B D` with `visit` directives on planets in each system, B's planet wouldn't be landed at the second time.

May look at oddities before `visit` stuff. Having trouble focusing right now though, as it's 29 C / 84 F in my flat right now.

**Comment by tehhowch** [comment]
I think as of 584f2d9 that NPCs which land permanently will no longer respawn when you launch a saved game (even though they still appear in the save file, they get an actions value and somehow don't spawn :man_shrugging: ). 
This doesn't yet cause missions to fail if they are supposed to be killed, so I'm going to leave the mission logic in your hands.

The NPCs still don't take full advantage of refueling prior to jumping if they are going to be out of fuel in the neighboring uninhabited system

**Comment by tehhowch** [comment]
I'm opting to remove the Survey stuff - there is already an in-game method for that, and it is the default behavior for `staying` ships with no hostile targets. This means we don't have to have a bunch of functions on the Ship class, and don't need new orders either: as you mentioned previously, we just need a time delay. We can adjust it on a per system basis, and additionally on if the ship is performing a patrol vs one-way navigation.

**Comment by tehhowch** [comment]
As of d369dff
 - Ships which should survey a system (e.g. patrol or waypoint) and also should land on a planet in that system (visit / land) will hold above their target for the duration of the survey, because the LAND_ON was being issued after the survey order. 
 - If a patrolling NPC ran out of fuel in an inhabited friendly system that was not also a stopover, it would not ask for help and would not attempt to land, resulting in it just being stuck. 
 - "Wandering" ships (e.g. uninterested with no TRAVEL_TO system) didn't know how to refuel themselves, but should be able to do this now.
 - Seemingly always related to running out of fuel, I've seen ships with patrol somehow stop patrolling. One that has fleeing (but no land directives in patrolled systems, so no permanent delete), and the other with heroic (both are uninterested, for testing).
 - Wandering ships do not consider the hostility of systems when jumping... the Deep River in my test mission happily went to Unfettered space on many occasions.

As of 7115ba0:
 - Check if we are surveying before issuing LAND_ON, and delaying the LAND_ON until we are done surveying.
The LAND_ON could be made to take priority by over the survey by keeping the LAND_ON check, and placing `npcShip.AbortSurvey()` before the `break;` statement. For `visit` situations, this would result in the survey being skipped if this system had both a stopover and a waypoint.
 - Fixed "stuck" ships by bringing in the refuel code from MoveEscort. Due to how the travel directives work, the NPCs werel not automatically telling themselves to land if they were parentless and had no fuel and had a goal system. Generic random walk NPCs had no idea refueling existing, much less anticipating running out of fuel, but now they do.
 - Did not observe the lost patrol behavior after addressing refueling issues. Probably is still present, but hard to pin down.
 - Considering destination hostility is probably an addition left for a separate PR
My current test mission file:
[npc_travel_to.txt](https://github.com/tehhowch/endless-sky/files/1095836/npc_travel_to.txt)

**Comment by tehhowch** [comment]
- [x] When surveying, if the ship had < 1 jump's worth of fuel, only the landable planet would be surveyed (e.g. continuously attempted to land on).
Fixed by gating the random selection of systems & planets by whether or not the ship is surveying
 - [x] `staying` ships that had a travel directive to land / visit some planet (potentially even in their current system, for visit) would lock onto a single stellar object and continuously try to land on it.
Fixed by adding a bool to verify that the targeted object can be landed on, which will generally fail, resulting in clearing the targeted stellarobject (e.g. the desired patrol-this-system behavior)
 - [ ] `staying` NPC with `land` or `visit` will - if they select a landable planet during the `staying` patrol, land on that planet, even if it is not one of their travel destinations.
We definitely need to allow these `staying` NPCs to land (otherwise any NPC that gets MoveIndependent won't be able to land to refuel), but perhaps it should be considered PEBKAC to specify `staying` in combination with `land` or `visit`.  We can also consider changing the HasTravelDirective() to a GetDestinationSystem() check (e.g. if there more travel to do, this ship is probably landing to refuel, so its OK), but then if the `land` or `visit` is in the final system, the ship will not land.


Also reordered checks in IssueNPCOrders to prevent iterating the map when the NPC is surveying, and also to prevent checking if a particular planet is in the system if it's already been landed on.

**Comment by tehhowch** [comment]
LocationFilter stuff now works for specifying the systems/planets for NPC travel :) Unlike the mission origin/destination filter, each successive filter is re-centered based on the previously chosen system.
e.g. distance 1 3 repeated 3 times would mean
1) distance 1 3 from the origin, 
2) distance 1 3 from location 1),
3) distance 1 3 from location 2).
This can't guarantee that the systems form some kind of logical path, but it helps.

I found an issue with routing if the ships can't reach the system in question, and sort-of remedied it. A better way would be to filter out invalids during NPC instantiation, but that would disallow using wormholes for system generation, which is a rather annoying limitation of the DistanceMap routine.
So instead the ships will delete invalid waypoints from their travel plans, so that (eventually) they only get valid waypoints.

test mission: 
[npc_travel_to.txt](https://github.com/tehhowch/endless-sky/files/1096890/npc_travel_to.txt)

**Comment by tehhowch** [comment]
I wrote up a few test missions: 
[npc_landevent_testmissions.txt](https://github.com/tehhowch/endless-sky/files/1107871/npc_landevent_testmissions.txt)

and also fixed a patrolling bug (d3bc73f), and separated IsDestroyed from HasLanded(). This way a ship which is landed cannot possibly trigger any events/actions/checks for reaching 0 or less hull. I don't think this was happening, but we guard against any such possibility by having them separate. As you mentioned, we could define some other method that checks for either, to serve as a space-saver and simplifier. (and the minuscule performance boost of only one class method call with 2 private vars vs two class method calls each with 1 private var).

**Comment by tehhowch** [comment]
When you get bored of working on GiftShip, @Elyssaen  :)
I am pretty sure we are at the fine-tuning tweak stage (making sure missions succeed/fail as expected), but a top-to-bottom inspection of travel logic can't hurt.

**Comment by tehhowch** [comment]
One thing that may be wish-listed for this is to ensure that "fleet movement" behavior is respected. Right now, all ships move independently. Since each has a parent (the player's flagship) that is not a part of their NPC block, this makes sense.

A solution may be to do some reparenting in Engine::Place. This reparenting may benefit upstream beyond the "enhanced" TravelTo "realism", in ensuring that hostile NPCs also act as fleets when moving to the player, even if they aren't using any of the mechanisms added here.

**Comment by tehhowch** [comment]
`entering` NPCs loaded from a save file (which did not get to perform their `entering` action) ignore their `entering` personality trait. This needs addressing

**Comment by tehhowch** [comment]
I've gotten `entering` to work properly, but the last bit that isn't working right is that a ship which is supposed to be `accompany (save)`, with land at a non-destination system, does not fail the mission if it lands on its preset target instead of sticking with the player.
One solution is to give `accompany` a failIf value of `(ShipEvent::DESTROY & ShipEvent::LAND)`, but this doesn't play well if the `land` target is the mission destination (e.g. in that case it should record as a success).

Additionally, if the success condition is `land`, and the target is the mission destination, the player has to wait for the NPC to land before landing in order to complete the mission. We either need to change this, or make it so that the ship doesn't spawn off of the planet when the player takes off again (e.g. doesn't visibly appear to have landed alongside the player).

**Comment by tehhowch** [comment]
Alright, i think i've addressed those cases with the latest commits.

I think the `land` success criterion and the disparity with it not completing if the player lands first can be solved in 2 ways:
1) Keep the current behavior, but make the ship appear to be still in orbit when taking off, by modifying Engine.cpp:
```
// Check whether this ship should take off with you.
if(isHere && !ship->IsDisabled()
		&& (player.GetPlanet()->CanLand(*ship) || ship->GetGovernment()->IsPlayer())
		&& !(ship->GetPersonality().IsStaying() || ship->GetPersonality().IsWaiting()
			|| (ship->GetStopovers().count(player.GetPlanet())
				&& !ship->GetStopovers().at(player.GetPlanet()))))
```
2) Modify the PlayerInfo::Land function to issue the ShipEvent::Land event by adding to the ShipEvent::DESTROY check, and moving it below where all healthy ships in system are placed on the planet:
https://github.com/tehhowch/endless-sky/blob/7f960045fa2a9fc16e00b5138d307aacd724434a/source/PlayerInfo.cpp#L925-L946

Keeping the existing behavior (ship must land first), and then modifying existing `Escort to ___` missions to indicate that the ships must land first, i.e. the player needs to provide protection while the NPC arrives and lands, removes the "cheese" of arriving early and then landing as soon as the escorts enter the system, but introduces a different "cheese": the player can simply hop to the next system and return after the landing has completed, so that there is no need to wait in the system and even have the escorted ship be under fire.
Both are solved by extending combat to systems that have a ship with `personality escort` present, but that is currently an unlikely proposition.

**Comment by tehhowch** [comment]
With the latest commit, the behavior of `master` is kept.

**Pull request closed without merging**
